### PR TITLE
issue 67: Resume search after a failure.

### LINKED ISSUE #67: Resumable searches when failing
* [ ] if the task fails then resume from the point we left off
* [ ] this might mean reading the current file to see where if go to, and possible re-searching some records
* [ ] self throttling, ie kill itself after an hour and let it re-spawn

### PR DESCRIPTION
**Pull request by picnicpete**
Thus far, we are only resuming the files search.

### CODE REVIEW

File: classes/file_search.php [hunk 1]
```diff
@@ -151,17 +151,20 @@ public static function get_criteria(files $record): object {
      *
      * @param \tool_advancedreplace\files $record
      * @param string $output path
-     * @param int $limitfrom limit for sql
-     * @param int $limitnum limit for sql
+     * @param int $startid minimum id for sql
+     * @param int $endid maximum id for sql
+     * @param bool $finalshard True if this is the ladt shard
```
Comment (bwalkerl) [inline classes/file_search.php:156]: Is finalshard needed? Logically I think it makes more sense to set endid to 0 for the final shard - since having it doesn't make sense if you're not going to use it. 

With that change it having a startid without an endid would be the indicator that it's the final shard.

File: classes/file_search.php [hunk 2]
```diff
@@ -171,23 +174,50 @@ public static function files(files $record, string $output = '', int $limitfrom
...
+            ];
+            fputcsv($stream, $columnheaders);
+        }
+
+        mtrace($logmessage);
         $record->set('timestart', time());
         $updatetime = time();
         $updatepercent = 0;
-        $matchcount = 0;
         $filecount = 0;
```
Comment (bwalkerl) [inline classes/file_search.php:218]: We're resetting the starttime, updatepercent and filecount for the resume. 

This will all work, it just resets progress back to 0. I think it's fine to leave this as is for now, but ideally we would calculate the filecount using the original percent, and also add this to totalfiles (this would also impact the ETA - which is why I'm leaning towards leaving it for later)

File: classes/file_search.php [hunk 3]
```diff
@@ -151,17 +151,20 @@ public static function get_criteria(files $record): object {
...
-     * @param int $limitfrom limit for sql
-     * @param int $limitnum limit for sql
+     * @param int $startid minimum id for sql
+     * @param int $endid maximum id for sql
+     * @param bool $finalshard True if this is the ladt shard
      * @return void
      */
-    public static function files(files $record, string $output = '', int $limitfrom = 0, int $limitnum = 0) {
+    public static function files(files $record, string $output = '',
+    int $startid = 0, int $endid = 0, bool $finalshard = false) {
```
Comment (bwalkerl) [inline classes/file_search.php]: indenting

File: classes/task/files.php [hunk 4]
```diff
@@ -63,30 +63,26 @@ public static function spawn_shards(\tool_advancedreplace\files $record): void {
...
         $timestart = time();
 
-        // Get the total number of files.
-        $criteria = \tool_advancedreplace\file_search::get_criteria($record);
-        [$whereclause, $params] = \tool_advancedreplace\file_search::make_where_clause($criteria);
-        $totalfiles = $DB->count_records_select('files', $whereclause, $params);
+        // The sharding will be controlled by ranges of the id column of the mdl_files table.
+        // Here we implement a simple division. In future we could use WHERE clause to choose more even break points.
+
+        $maxid = $DB->get_field_sql('SELECT MAX(id) FROM {files}');
```
Comment (bwalkerl) [inline classes/task/files.php:69]: This is something we agreed upon, but I'm still not convinced that splitting the shards like this is an improvement.

Would it be too inefficient to do a full count and have subsequent selects getting the max id with the where clause with the start id and a limit based on totalcount/numshards?

File: classes/file_search.php [hunk 5]
```diff
@@ -616,6 +646,79 @@ public static function make_where_clause(object $criteria): array {
...
+                // Leave this line in place.
+                break;
+            }
+            if ( count($lines) < 3 ) {
+                // Too small to resume.
+                return [0, 0];
+            }
+        }
+        // Re-write the file, without the matched id lines.
+        file_put_contents($filename, implode("\n", $lines) . "\n");
```
Comment (bwalkerl) [inline classes/file_search.php]: If this is running on a non linux system would the original lines be split differently? If so would PHP_EOL be the better option?

**Review by bwalkerl — COMMENTED** [review]
Thanks @picnicpete this was working as intended in my local testing. Just a few comments.

File: classes/file_search.php (hunk 1 above)
Comment (picnicpete) [reply classes/file_search.php:156]: Well I think this is a program style question.  My preference is to code explicitly, as I have done.  Over-loading the endid to have a special meaning when it is null or zero is a bit obscure. 
With the finalshard parameter and variable it is obvious to all what we are intending.

File: classes/file_search.php (hunk 2 above)
Comment (picnicpete) [reply classes/file_search.php:218]: I agree about leaving it for later.  Then, how about putting the totalfiles and filecount in the record?  Again, that is explicit coding.

File: classes/file_search.php (hunk 3 above)
Comment (picnicpete) [reply classes/file_search.php]: :(  This is how phpcbf made it.  I will fix.

File: classes/task/files.php (hunk 4 above)
Comment (picnicpete) [reply classes/task/files.php:69]: Yes - I proposed doing all the counting in the master shard and giving the children id numbers to work with.  The split will be quite uneven as we have it.  The first 50 percent will be approximately empty. But this is actually not much of a disaster. We can just run it with a bigger number of shards. 

I don't think PR comments is the place to change the specs.

File: classes/file_search.php (hunk 5 above)
Comment (picnicpete) [reply classes/file_search.php]: OK. I will fix this.

File: classes/file_search.php (hunk 1 above)
Comment (bwalkerl) [reply classes/file_search.php:156]: That's fair. 

I think the main point I was trying to make is more that we shouldn't be setting an endid if we're not going to use it - which I'd argue actually makes it less explicit. I can agree with the confusion about the default being 0 now that this has been changed to endid, but a check on start or end id being provided would be trivial and self explanatory.

Anyway it's not worth going into this too deeply, I'm OK with keeping it if you have a strong preference.

File: classes/file_search.php (hunk 3 above)
Comment (bwalkerl) [reply classes/file_search.php]: I think this still needs further indents after the first fix based on https://moodledev.io/general/development/policies/codingstyle#wrapping-of-the-function-signatures

File: classes/file_search.php (hunk 2 above)
Comment (bwalkerl) [reply classes/file_search.php:218]: It's an option, but as this is just for progress and estimates are fine I don't think we actually need to be explicit here. timeresumed may be needed for the ETA though. But lets leave this for later.

File: classes/task/files.php (hunk 4 above)
Comment (bwalkerl) [reply classes/task/files.php:69]: I mainly brought it up because in my mind this is a pretty big regression when the number of processes running at a time are limited, especially if everything ends up being in one small section. 

But I agree it is as per the current spec and it's OK for our current purposes so I'm OK with merging.
