### PR TITLE
Issue #109: Make replacements idempotent and improve feedback

### LINKED ISSUE #109: All replacements should be idempotent and report success if has worked both the first time AND the second time
Lets say I want to replace 'foo' with 'bar' and this applies to both the db replace and the file replace.

If I cannot find 'foo' then it is an error and we increment and show that.

But lets say we do find 'foo' and replace it, then we increment the number of success and keep going.

If I upload a test file and do a replace then I get this:

`Replaced 1 rows. Skipped 0 rows. Error replacing 0 rows.`

If I upload the exact same file again then I get the exact same message:

`Replaced 1 rows. Skipped 0 rows. Error replacing 0 rows.`

So clearly its feedback is wrong, if the first one succeded then the second one should be

`Replaced 0 rows. Skipped 0 rows. Error replacing 1 rows.`

* [ ] But nothing actually happened so I don't trust the replace feedback. So I want to actually check the new text we have replaced for the contents of the 'replace' field to confirm it actually ended up in there or not.
* [ ] I want a 4th counter which is for content where we didn't find the match BUT we did find the replacement. ie we've run this file before. In this case it is kinda a success because we have the outcome we want, its not a true error and if we did a huge batch of 100s of replaces and for whatever reason some didn't work (eg db died or php timed out) and we re-run it, then we want to end up with 100% successful replacement and we don't mind so much if it did the replace the first or the second time.

### PR DESCRIPTION
**Pull request by petersistrom**
Resolves #109

### CODE REVIEW

File: classes/helper.php [hunk 1]
```diff
@@ -781,19 +786,21 @@ public static function handle_replace_csv(string $data, string $type = 'db') {
...
         $csvimport->init();
-        $rowcount = 0;
-        $rowskip = 0;
-        $rowerror = 0;
+        $rowcounts = [
+            'success' => 0,
+            'skipped' => 0,
+            'error' => 0,
+            'replacematch' => 0,
+            ];
```
Comment (brendanheywood) [inline classes/helper.php]: generally indent the ] back up a level

File: classes/helper.php [hunk 2]
```diff
@@ -805,20 +812,28 @@ public static function handle_replace_csv(string $data, string $type = 'db') {
...
+                    $record[$internalindex], $rowcounts);
             }
-
+            $totalrows++;
             // Update the progress bar.
-            $rowcount++;
-            $progress->update_full(100 * $rowcount / $contentcount,
-                "Replaced $rowcount rows. Skipped $rowskip rows. Error replacing $rowerror rows.");
+            $progress->update_full(
+                100 * $totalrows / $contentcount,
```
Comment (brendanheywood) [inline classes/helper.php]: can you refactor this long string with the same long string below?

also I think its too long, needs to be < 80 chars

**Review by brendanheywood — APPROVED** [review]
